# -*- coding: utf-8 -*-
"""Chiavi mancanti del namespace reports (erano tutte grezze in pagina)."""
import io
import json
import os

KEYS = {
    'it': [
        ('schedules', 'Report programmati'),
        ('configureReport', 'Configura report'),
        ('audience', 'Destinatario'),
        ('audienceStaff', 'Staff tecnico'),
        ('audienceMedical', 'Staff medico'),
        ('audienceTrainer', 'Preparatore'),
        ('team', 'Squadra'),
        ('allTeams', 'Tutte le squadre'),
        ('athlete', 'Atleta'),
        ('wholeTeam', 'Tutta la squadra'),
        ('athleteReportHint', 'Il report verrà calcolato solo su questo atleta: sessioni, carichi, wellness e infortuni riferiti a lui.'),
        ('from', 'Dal'),
        ('to', 'Al'),
        ('includeAISummary', 'Includi sintesi AI'),
        ('preview', 'Anteprima'),
        ('generating', 'Generazione…'),
        ('downloadPdf', 'Scarica PDF'),
        ('downloadDocx', 'Scarica Word'),
        ('organization', 'Organizzazione'),
        ('periodLabel', 'Periodo'),
        ('generatedBy', 'Generato da'),
        ('aiSummary', 'Sintesi AI'),
        ('viewFullJson', 'Vedi il JSON completo'),
        ('toastPreviewGenerated', 'Anteprima generata'),
        ('toastDownloaded', 'File {format} scaricato'),
        ('toastError', 'Errore'),
        ('toastUnknownError', 'Errore sconosciuto'),
        ('toastDownloadError', 'Errore durante il download'),
        ('toastSessionExpired', 'Sessione scaduta, esegui di nuovo l’accesso'),
        ('toastEmptyFile', 'Il server ha restituito un file vuoto'),
    ],
    'en': [
        ('schedules', 'Scheduled reports'),
        ('configureReport', 'Configure report'),
        ('audience', 'Audience'),
        ('audienceStaff', 'Technical staff'),
        ('audienceMedical', 'Medical staff'),
        ('audienceTrainer', 'Strength coach'),
        ('team', 'Team'),
        ('allTeams', 'All teams'),
        ('athlete', 'Athlete'),
        ('wholeTeam', 'Whole team'),
        ('athleteReportHint', 'The report will cover this athlete only: sessions, loads, wellness and injuries related to them.'),
        ('from', 'From'),
        ('to', 'To'),
        ('includeAISummary', 'Include AI summary'),
        ('preview', 'Preview'),
        ('generating', 'Generating…'),
        ('downloadPdf', 'Download PDF'),
        ('downloadDocx', 'Download Word'),
        ('organization', 'Organisation'),
        ('periodLabel', 'Period'),
        ('generatedBy', 'Generated by'),
        ('aiSummary', 'AI summary'),
        ('viewFullJson', 'View full JSON'),
        ('toastPreviewGenerated', 'Preview generated'),
        ('toastDownloaded', '{format} file downloaded'),
        ('toastError', 'Error'),
        ('toastUnknownError', 'Unknown error'),
        ('toastDownloadError', 'Download failed'),
        ('toastSessionExpired', 'Session expired, please sign in again'),
        ('toastEmptyFile', 'The server returned an empty file'),
    ],
    'es': [
        ('schedules', 'Informes programados'),
        ('configureReport', 'Configurar informe'),
        ('audience', 'Destinatario'),
        ('audienceStaff', 'Cuerpo técnico'),
        ('audienceMedical', 'Cuerpo médico'),
        ('audienceTrainer', 'Preparador físico'),
        ('team', 'Equipo'),
        ('allTeams', 'Todos los equipos'),
        ('athlete', 'Atleta'),
        ('wholeTeam', 'Todo el equipo'),
        ('athleteReportHint', 'El informe se calculará solo sobre este atleta: sesiones, cargas, wellness y lesiones referidas a él.'),
        ('from', 'Desde'),
        ('to', 'Hasta'),
        ('includeAISummary', 'Incluir resumen de IA'),
        ('preview', 'Vista previa'),
        ('generating', 'Generando…'),
        ('downloadPdf', 'Descargar PDF'),
        ('downloadDocx', 'Descargar Word'),
        ('organization', 'Organización'),
        ('periodLabel', 'Periodo'),
        ('generatedBy', 'Generado por'),
        ('aiSummary', 'Resumen de IA'),
        ('viewFullJson', 'Ver el JSON completo'),
        ('toastPreviewGenerated', 'Vista previa generada'),
        ('toastDownloaded', 'Archivo {format} descargado'),
        ('toastError', 'Error'),
        ('toastUnknownError', 'Error desconocido'),
        ('toastDownloadError', 'Error durante la descarga'),
        ('toastSessionExpired', 'Sesión caducada, vuelve a iniciar sesión'),
        ('toastEmptyFile', 'El servidor ha devuelto un archivo vacío'),
    ],
}

for d in ['trainmind-app/apps/web/src/messages', 'trainmind-mobile/web/src/messages']:
    for loc, pairs in KEYS.items():
        path = os.path.join(d, loc + '.json')
        src = io.open(path, encoding='utf-8', newline='').read()
        nl = '\r\n' if '\r\n' in src else '\n'
        ns = json.loads(src).get('reports')
        if ns is None:
            print('SKIP (no reports ns)', path)
            continue

        # àncora: la riga "newReport" del namespace reports
        anchor = None
        for line in src.split(nl):
            if '"newReport"' in line:
                anchor = line
                break
        if anchor is None:
            print('SKIP (no anchor)', path)
            continue

        added = ['    %s: %s,' % (json.dumps(k, ensure_ascii=False), json.dumps(v, ensure_ascii=False))
                 for k, v in pairs if k not in ns]
        if not added:
            print('OK (already patched)', path)
            continue

        out = src.replace(anchor, anchor + nl + nl.join(added), 1)
        json.loads(out)
        io.open(path, 'w', encoding='utf-8', newline='').write(out)
        print('patched %-2s %s (+%d)' % (loc, path, len(added)))
